export type TextColor = 'on-primary'
    | 'on-primary-container'
    | 'on-secondary'
    | 'on-secondary-container'
    | 'on-tertiary'
    | 'on-tertiary-container'
    | 'on-primary-fixed'
    | 'on-primary-fixed-variant'
    | 'on-secondary-fixed'
    | 'on-secondary-fixed-variant'
    | 'on-tertiary-fixed'
    | 'on-tertiary-fixed-variant'
    | 'on-error'
    | 'on-error-container'
    | 'on-surface'
    | 'on-surface-variant'
    | 'inverse-on-surface';